version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nz01
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/src
  #     - ./config/nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - web
  #   networks:
  #     - djangonetwork
  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - db
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    # links:
    #   - redis
    env_file:
      - .envs/.django
    networks:
      - djangonetwork
  db:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    env_file:
      - .envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork
    ports:
      - "5432:5432"
  # redis:
  #   image: redis:alpine
  #   container_name: rz01
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - djangonetwork

networks:
  djangonetwork:
    driver: bridge
