version: "3"

services:
  postgres:
    image: postgres:13.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=prospect
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prospect
    ports:
      - "5432:5432"
    networks:
      - default

  prospect_api:
    image: nmsilva90s/housepref-api:latest
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn mydjango.wsgi -b 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    volumes:
      - ./api/media/:/src/media/
      - ./api/backups/:/backups/
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_USER=prospect
      - DB_NAME=prospect
      - CLIENT_BASE_URL=https://dcspt-getin.ua.pt/prospect/
      - ADMIN_URL_PREFIX=prospect/
      - STATIC_URL_PREFIX=/prospect
      - MEDIA_URL_PREFIX=https://dcspt-getin.ua.pt/prospect
      - SENDGRID_API_KEY=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
      - EMAIL_FROM=dcspt-getin@ua.pt
      - DEBUG=0
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: {}
