# Generated by Django 3.1.4 on 2022-06-04 07:27

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorialCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('municod', models.CharField(blank=True, max_length=60)),
                ('aditional_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('NOT_COMPLETED', 'Not Completed')], default='NOT_COMPLETED', max_length=30)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TerritorialUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('tucode', models.CharField(blank=True, max_length=60)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NOT_ACTIVE', 'Not Active')], default='ACTIVE', max_length=30)),
                ('territorial_coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='housearch.territorialcoverage')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TerritorialUnitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('image_url', models.CharField(blank=True, max_length=60)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('territorial_unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housearch.territorialunit')),
            ],
            options={
                'permissions': (),
            },
        ),
    ]
