# Generated by Django 3.1.4 on 2022-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorialunitimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
