# Generated by Django 3.1.4 on 2021-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
                ('language_code', models.CharField(max_length=256)),
                ('translations', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
