# Generated by Django 3.1.4 on 2022-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_questionoption_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativada'), ('NOT_ACTIVE', 'Desativada')], default='ACTIVE', max_length=30),
        ),
    ]
