# Generated by Django 3.1.4 on 2022-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_selection_type',
            field=models.CharField(blank=True, choices=[('RADIO', 'Radio'), ('SELECT', 'Select')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(blank=True, choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('SLIDER', 'Slider')], default=None, max_length=30),
        ),
    ]
