# Generated by Django 3.1.4 on 2022-02-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220211_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='row_order',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
