# Generated by Django 3.1.4 on 2022-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_questionoption_row_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='row_order',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
