# Generated by Django 3.1.4 on 2022-02-17 10:07

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0008_auto_20220217_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
