# Generated by Django 3.1.4 on 2022-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_description_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
