# Generated by Django 3.1.4 on 2022-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_question_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value_interval',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
