# Generated by Django 3.1.4 on 2022-02-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_question_value_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value_interval',
            field=models.CharField(blank=True, default='1', max_length=60, null=True),
        ),
    ]
