# Generated by Django 3.1.4 on 2022-03-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220228_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
