# Generated by Django 3.1.4 on 2022-03-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_question_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['rank', '-id'], 'permissions': ()},
        ),
        migrations.AddField(
            model_name='question',
            name='correct_value',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
