# Generated by Django 3.1.4 on 2022-03-10 22:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220310_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_label',
            field=models.JSONField(blank=True, default=core.models.input_label_default_value, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='input_size',
            field=models.CharField(blank=True, default='16', max_length=56),
        ),
    ]
