# Generated by Django 3.1.4 on 2022-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220315_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AddField(
            model_name='question',
            name='groups',
            field=models.ManyToManyField(to='core.GroupQuestions'),
        ),
    ]
