# Generated by Django 3.1.4 on 2022-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220315_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['row_order'], 'permissions': ()},
        ),
        migrations.AddField(
            model_name='groupquestions',
            name='user_group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ONLY_QUESTION_INFO', 'Somente informação'), ('MULTIPLE_CHOICE', 'Escolha múltipla'), (
                'SHORT_ANSWER', 'Resposta curta'), ('PAIRWISE_COMBINATIONS', 'Combionações par a par')], default=None, max_length=60),
        ),
    ]
