# Generated by Django 3.1.4 on 2022-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220325_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='multiple_selection_type',
            field=models.CharField(blank=True, choices=[('RADIO', 'Radio'), ('SELECT', 'Select'), ('MULTIPLE_VALUES', 'Multiple')], default=None, max_length=30),
        ),
    ]
