# Generated by Django 3.1.4 on 2022-03-28 20:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220325_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_html',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
