# Generated by Django 3.1.4 on 2022-03-30 07:18

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(
        key='CONSISTENCY_RATIO_MATRIX', value='{ "3": 0.525, "4": 0.882, "5": 1.11, "6": 1.25 }')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220328_2038'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
