# Generated by Django 3.1.4 on 2022-04-19 17:44

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(
        key='CORRELATION_LIMIT_VALUE', value='0.5')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_groupquestions_is_visible_on_results'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
