# Generated by Django 3.1.4 on 2022-05-05 11:11

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(
        key='SHOW_RESULTS_AFTER', value='')
    Configuration.objects.create(
        key='SHOW_RESULTS_BEFORE', value='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220419_1744'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
