# Generated by Django 3.1.4 on 2022-06-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220604_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ONLY_QUESTION_INFO', 'Somente informação'), ('MULTIPLE_CHOICE', 'Escolha múltipla'), ('SHORT_ANSWER', 'Resposta curta'), ('PAIRWISE_COMBINATIONS', 'Combionações par a par'), ('URBAN_SHAPES', 'Urban Shapes'), ('CITIZEN_PROFILE', 'Citizen Profile')], default=None, max_length=60),
        ),
    ]
