# Generated by Django 3.1.4 on 2022-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220604_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ONLY_QUESTION_INFO', 'Somente informação'), ('MULTIPLE_CHOICE', 'Escolha múltipla'), ('SHORT_ANSWER', 'Resposta curta'), ('PAIRWISE_COMBINATIONS', 'Combinações par a par'), ('IMAGE_PAIRWISE_COMBINATIONS', 'Combinações de imagens par a par'), ('CITIZEN_PROFILE', 'Citizen Profile')], default=None, max_length=60),
        ),
    ]
