# Generated by Django 3.1.4 on 2022-06-17 17:49

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(key='PROFILE_QUESTIONS_SHOW_KEYS', value='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220617_1743'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
