# Generated by Django 3.1.4 on 2022-06-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220617_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('ONLY_QUESTION_INFO', 'Somente informação'), ('MULTIPLE_CHOICE', 'Escolha múltipla'), ('SHORT_ANSWER', 'Resposta curta'), ('PAIRWISE_COMBINATIONS', 'Combinações par a par'), ('IMAGE_PAIRWISE_COMBINATIONS', 'Combinações de imagens par a par'), ('CITIZEN_PROFILE', 'Citizen Profile'), ('TERRITORIAL_COVERAGE', 'Escolha de cobertura territorial'), ('GEOLOCATION', 'Escolha de Geolocalização')], default=None, max_length=60),
        ),
    ]
