# Generated by Django 3.1.4 on 2022-07-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220617_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_pairwise_type',
            field=models.CharField(blank=True, choices=[('BINARY_CHOICE', 'Escolha Binária'), ('WEIGHT_BASED_CHOICE', 'Escolha com base em peso')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='show_balance',
            field=models.BooleanField(default=True),
        ),
    ]
