# Generated by Django 3.1.4 on 2022-07-20 16:16

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(
        key='DEFAULT_USER_GROUP', value='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_question_territorial_coverages'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
