# Generated by Django 3.1.4 on 2022-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_question_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'permissions': (), 'verbose_name': 'Global Configuration', 'verbose_name_plural': 'Global Configurations'},
        ),
        migrations.AlterModelOptions(
            name='groupquestions',
            options={'permissions': (), 'verbose_name': 'Group of Questions', 'verbose_name_plural': 'Groups of Questions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='question',
            name='use_360_image',
            field=models.BooleanField(default=True, verbose_name='Show 360 Image'),
        ),
    ]
