# Generated by Django 3.1.4 on 2022-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20220822_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='use_360_image',
            field=models.BooleanField(default=False, verbose_name='Show 360 Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='use_google_street_images',
            field=models.BooleanField(default=False, verbose_name='Show Google Street Images'),
        ),
    ]
