# Generated by Django 3.1.4 on 2022-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20220822_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_only_on_parent_value',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Show only if parent value is equals (values separated with commas)'),
        ),
    ]
