# Generated by Django 3.1.4 on 2022-09-30 06:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_question_show_only_on_parent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slider_label',
            field=models.JSONField(blank=True, default=core.models.slider_label_default_value, null=True),
        ),
    ]
