# Generated by Django 3.1.4 on 2022-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_question_slider_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='disabled_after_filled',
            field=models.BooleanField(default=True, verbose_name='Disabled after filled'),
        ),
    ]
