# Generated by Django 3.1.4 on 2022-10-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housearch', '0003_auto_20220822_1515'),
        ('core', '0047_question_disabled_after_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='territorial_unit_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='territorial_unit_images', to='housearch.territorialunitimage'),
        ),
    ]
