# Generated by Django 3.1.4 on 2022-11-14 14:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_question_territorial_unit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
