# Generated by Django 3.1.4 on 2022-06-04 07:25

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(key='PROLIFIC_COMPLETION_URL', value='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_page_header_menu'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
