# Generated by Django 3.1.4 on 2023-01-07 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_auto_20230106_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'permissions': (), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='userintegration',
            options={'permissions': (), 'verbose_name': 'User Integration', 'verbose_name_plural': 'User Integrations'},
        ),
        migrations.AddField(
            model_name='question',
            name='option_to_finish',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Option id to send user to the end'),
        ),
        migrations.AlterField(
            model_name='userintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
