# Generated by Django 3.1.4 on 2023-01-30 17:22

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(key='SHOW_RESTART_QUESTIONS_BUTTON', value='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20230117_1959'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
