# Generated by Django 3.1.4 on 2023-01-30 17:29

from django.db import migrations


def insert_configurations(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Configuration = apps.get_model('core', 'Configuration')

    Configuration.objects.create(
        key='GOOGLE_IMAGE_RESOLUTION_WIDTH', value='600')
    Configuration.objects.create(
        key='GOOGLE_IMAGE_RESOLUTION_HEIGHT', value='600')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20230130_1722'),
    ]

    operations = [
        migrations.RunPython(insert_configurations, migrations.RunPython.noop)
    ]
