# Generated by Django 3.1.4 on 2023-06-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_page_is_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_chars',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_chars',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
