# Generated by Django 3.1.4 on 2023-06-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20230626_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='embedded_question_url',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Embeded Question External Url'),
        ),
    ]
