# Generated by Django 3.1.4 on 2023-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20230626_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='embedded_size',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
