# Generated by Django 3.1.4 on 2023-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20230627_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
